// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// DATABASE_URL lives only in the root .env, not apps/api/.env (see
// apps/api/.env.example). Plain `dotenv/config` only loads a `.env` from the
// current working directory, so it misses the root file when the Prisma CLI
// is invoked from the apps/api workspace. Reuse the same multi-path loader
// the API itself uses, so both always resolve DATABASE_URL from the same
// root .env and can never point at different databases.
import './src/config/load-environment';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
